user_sessions = {}
messages = {}
room_users = {}
banned_ips = set()
banned_usernames = set()
user_ips = {}
kicked_users = {}
room_owners = {}
public_chat_rooms = []
video_state = {}

regional_chat_rooms = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]

topical_chat_rooms = [
    "Tech",
    "Science",
    "Gaming",
    "Movies",
    "Music",
    "Books",
    "Current Events",
    "Sports",
    "Travel",
    "Food & Cooking",
    "Health & Fitness",
    "History",
    "Programming",
    "Investing",
    "Cryptocurrency",
    "Parenting",
    "DIY & Home Improvement",
    "Photography",
    "Fashion",
    "Automotive",
    "Theater & Performing Arts",
    "Pets & Animals",
    "Space Exploration",
    "Climate Change",
    "Entrepreneurship",
    "Relationships",
    "Comics & Manga",
    "Anime",
    "Board Games",
    "Card Games",
    "Tabletop RPGs",
    "Language Learning",
    "Economics",
    "Politics",
    "Fan Theories",
    "Science Fiction",
    "Fantasy",
    "Artificial Intelligence",
    "Web Development",
    "Mobile Apps",
    "Cybersecurity",
    "3D Printing",
    "Virtual Reality",
    "Augmented Reality",
    "Home Automation",
    "Sustainable Living",
]
